// metiersFreework.js — référentiel de métiers (onglet « FreeWork_Metiers » de
// input/referentiel_skills/referentiels_skills.xlsx, 137 entrées, artefacts numériques retirés).
// Généré — ne pas éditer à la main. Alimente le champ Intitulé du poste (autocomplete).
export const METIERS = [
  "Acheteur·euse", "Administrateur·rice d'application (progiciel ERP, CRM, SIRH ...)",
  "Administrateur·rice de base de données (Oracle, Sybase, Sqlserver...)",
  "Administrateur·rice de site Web (webmaster)", "Administrateur·rice réseaux",
  "Administrateur·rice sécurité", "Administrateur·rice système Unix (linux...)",
  "Administrateur·rice système Windows", "Analyste programmeur·euse", "Analyste web analytics",
  "Architecte Cloud", "Architecte d'entreprise / urbaniste SI", "Architecte de base de données",
  "Architecte réseaux", "Architecte solutions", "Architecte système d'information",
  "Architecte technique", "Assistant·e chef·fe de projet", "Auditeur·rice", "Autre",
  "Business analyst", "Chargé·e d'affaire", "Chargé·e de recrutement IT",
  "Chef·fe de projet digital", "Chef·fe de projet e-commerce", "Chef·fe de projet informatique",
  "Chef·fe de projet systèmes et réseaux", "Chef·fe de projet télécommunication",
  "Chef·fe de projet TMA (Tierce Maintenance Applicative)", "Chercheur·euse en informatique",
  "Coach agile", "Community manager / social media manager",
  "Concepteur·rice et analyste de base de données", "Concepteur·rice multimédia",
  "Concepteur·rice rédacteur·rice",
  "Consultant·e décisionnel / Business Intelligence (PowerBI, SAS, Tableau...)",
  "Consultant·e e-business", "Consultant·e en architecture", "Consultant·e en cybersécurité",
  "Consultant·e ERP (MS Dynamics, Oracle, Sage, SAP...)",
  "Consultant·e fonctionnel / métier (ecommerce, RH, finance, supply chain, BPM, achat...)",
  "Consultant·e Microsoft (Office, SharePoint, 365...)", "Consultant·e MOA/AMOA",
  "Consultant·e progiciel / applicatif (CRM, RH, finance...)", "Consultant·e SEA / Traffic Manager",
  "Consultant·e système d'information géographique (SIG/GIS)", "Consultant·e technique",
  "Content manager", "Data analyst", "Data scientist", "Développeur·euse .Net (C# ...)",
  "Développeur·euse / Intégrateur·rice de progiciel (ERP, CRM, Dynamics, Oracle, Salesforce, SAP, Sage, SharePoint, Sybase...)",
  "Développeur·euse autre langage (R, Cobol, Perl, VBA, Ruby, Shell...)",
  "Développeur·euse base de données (SQL, PL/SQL, Oracle...)", "Développeur·euse C, C++",
  "Développeur·euse data (décisionnel / BI / Big Data / Data engineer)",
  "Développeur·euse fonctionnel (Scala, LISP, ML, Haskell, OCaml, F#, Erlang, Clojure)",
  "Développeur·euse front-end (JavaScript, Node, React, Angular, Vue...)",
  "Développeur·euse fullstack", "Développeur·euse IA/Machine Learning",
  "Développeur·euse Java (Kotlin, Groovy...)", "Développeur·euse jeux vidéos",
  "Développeur·euse logiciel de réalité augmentée",
  "Développeur·euse logiciel embarqué (IoT, assembleur, microcontrôleur...)",
  "Développeur·euse mobile Android", "Développeur·euse mobile iOS (Swift, Objective-C...)",
  "Développeur·euse PHP (Symfony, Laravel, Drupal...)", "Développeur·euse Python",
  "Développeur·euse sécurité (devsecops)",
  "Directeur·rice / Responsable de département (de division, service)",
  "Directeur·rice / Responsable de la data (Chief Data Officer)",
  "Directeur·rice / Responsable de la transformation digitale (CDO)",
  "Directeur·rice / Responsable de projet", "Directeur·rice / Responsable e-commerce",
  "Directeur·rice / Responsable informatique",
  "Directeur·rice / Responsable marketing online (Chief Marketing Officer)",
  "Directeur·rice commercial", "Directeur·rice des systèmes d'information (DSI)",
  "Directeur·rice technique (des nouvelles technologies, CTO)",
  "Expert·e / Consultant·e SEO (référencement)", "Expert·e accessibilité", "Expert·e monétique",
  "Expert·e protection des données (RGPD, DPO)", "Formateur·rice", "Game designer",
  "Gestionnaire de prestation de services (Service Delivery Manager)", "Homologateur·rice logiciel",
  "Incident Manager", "Infographiste", "Ingénieur·e après-vente", "Ingénieur·e d'études",
  "Ingénieur·e d'exploitation", "Ingénieur·e de production", "Ingénieur·e devops (Cloud)",
  "Ingénieur·e en cybersécurité", "Ingénieur·e informatique industrielle",
  "Ingénieur·e qualité et méthodes", "Ingénieur·e R&D", "Ingénieur·e systèmes & réseaux",
  "Ingénieur·e technico-commercial (avant-vente...)", "Ingénieur·e télécommunication",
  "Ingénieur·e télématique", "Ingénieur·e test et recette (testeur·euse QA)",
  "Intégrateur·rice d'application", "Intégrateur·rice web (HTML, CSS)",
  "Lead developer / Tech lead", "Level designer", "Manager de transition", "Manager IT",
  "Maquettiste PAO", "Modeleur·euse / Animateur·rice 3D", "Product owner",
  "Project Management Officer (PMO)",
  "Pupitreur·euse / Opérateur·rice / Pilote / Analyste d'exploitation",
  "Responsable / Gestionnaire d'application", "Responsable commercial·e / de compte",
  "Responsable d'exploitation (data center)", "Responsable de parc informatique",
  "Responsable des infrastructures et de la production", "Responsable maintenance informatique",
  "Responsable produit (Product Manager, Chief Product Officer)",
  "Responsable qualité (QA Manager)", "Responsable R&D", "Responsable sécurité informatique (CISO)",
  "Responsable systèmes et réseaux", "Responsable technique", "Responsable télécom", "Scrum master",
  "Support utilisateurs (bureautique, hot liner, helpdesk, poste de travail...)",
  "Technicien·ne d'exploitation",
  "Technicien·ne de maintenance micro-informatique (bureautique, poste de travail...)",
  "Technicien·ne réseau", "Technicien·ne télécom", "Testeur·euse de jeux vidéo",
  "UI designer / Directeur·rice artistique / Webdesigner",
  "UX designer / Concepteur·rice d'interface / Ergonome", "Web planneur"
];
